### GET a list of campsites
GET http://localhost:8000/api/camping

### POST a new campsite
POST http://localhost:8000/api/camping
Content-Type: application/json

{
  "camping1": {
    "firstname": "Charlotte",
    "lastname": "Hilton",
    "company": "Epsilon Hotel"
  }
}

### POST a new admin
POST http://localhost:8000/api/admin
Content-Type: application/json

{
  "company": "Hilton Hotel",
  "firstname": "Vico",
  "lastname": "Latino",
}